name: Create AMSDA.txt file with AMSDA content

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: echo "This is a setup step"

      - name: Helper Step
        run: echo "Remember to create a file called AMSDA.txt with content AMSDA"
