name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # SETUP INSTRUCTION: Before running this workflow,
      # Create a file called AMSDA.txt with the text "AMSDA WAS HERE"
      - name: Install dependencies
        run: pip install -r requirements.txt
